### ISSUE TITLE
Why this lib instead of TinyGSM?

### ISSUE THREAD

**Issue by bwjohns4** [zimbora/esp32-BG95#2]
Is there anything that differentiates this from the TinyGSM library? I do see that TinyGSM hasn't been updated for a while and also does not seem to support SSL on BG95 so that's great! I was just wondering if anything else about this effort is largely different than just using TinyGSM.

Also, I'm curious if this is a brand new implementation or if it has been time tested at all to date. It looks very good with LOTS of features, just wondering if it came from anywhere else or has been used for long.

**Comment by zimbora** [comment]
I have been using most of the code since Quectel launched this module (maybe 2 years). Before that, part of this library was largely used with sim800c. 
To sum, this is a fork of an internal library used in several projects and which is running in hundreds of devices.

Why this and not TinyGSM? My advice is to use TinyGSM if you are building an ecossystem for multi modems. However, if your aim is to work only with BG95 or quectel modems with qualcomm chipset I think you should consider this library.

It will allow your code to have multiple contexts with operator (you can have a private apn and a public apn simultaneously).
It supports multiple tcp connection and even multiple mqtt connection (also tested).
MQTT protocol is handled in BG95 socket releasing resources for your uController (memory and cpu).

Also you can switch between different radio technologies (GSM/GPRS/NB/CATM1) or define auto modes.

I will also add DFOTA for modem, allready tested by me. This is only possible with quectel support.
Yesterday I added HTTP/HTTPS GET and Post methods with json support and possibility to add new parameters to header

But if this is not enough :) you can also take a look to a new repo that I am working on :
- [https://github.com/zimbora/esp32-modem-freeRTOS](esp32-modem-freeRTOS)

which uses freeRTOS to create a task just to interact with the modem while the other tasks do what they have to do without interruptions

**Comment by bwjohns4** [comment]
Wow! This is incredible! Thanks for posting this!

**Comment by bwjohns4** [comment]
When is it appropriate to use the freeRTOS version of this? I was thinking of just running the loop() part of this (esp32-BG95) library on it's own task. Will this not work just running basically these examples on their own freeRTOS task? At what point do you run into complications where it makes sense to go with the full freeRTOS version?

**Comment by zimbora** [comment]
Sometimes modem takes several seconds to answer to at commands, this is a block event. If you need to update an lcd every second or listen for touch events you will miss that.
To use freeRTOS you will have to share buffers between processes, having a concurrency problem. So, if you do not deal with it, it is likely that some writes will fail.
