### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Colphonius** [zimbora/esp32-BG95#8]
Would the software would work with other Quectel BG modems, e.g. BG600L?

**Comment by zimbora** [comment]
I had tested BG600L with the following repository [link](https://github.com/zimbora/stm32l4xx-BG95)

Both libraries are too similar, yet BG600L have some limitations regarding to http protocol and mqtt buffer capabilities.
HTTP issues were not solved, I reported the issue to quectel to improve their code. I have no further information since there.

Regarding to MQTT I think this library now will do the work correctly.

So, I expect that BG600L will work fine with this library for most of the cases. If you want to test and contribute to this library feel free to do it ;)
